# Generated by Django 4.0.2 on 2022-10-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(upload_to='menu_images/')),
            ],
            options={
                'verbose_name': 'foodcategory',
                'verbose_name_plural': 'foodcategories',
                'ordering': ('name',),
            },
        ),
    ]
